### ISSUE TITLE
Can't build on ghc-7.6.2

### ISSUE THREAD

**Issue by ierton** [ajhc/drift#1]
Hi. I am trying to build DriFT in order to compile ajhc from git. Unfortunately,
an error have appeared:

```
dev:[ierton@greyblade:~/tmp/drift]$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.6.2

dev:[ierton@greyblade:~/tmp/drift]$ cabal build
Building DrIFT-cabalized-2.2.3.3...
Preprocessing executable 'DrIFT-cabalized-ghc' for
DrIFT-cabalized-2.2.3.3...
Preprocessing executable 'DrIFT-cabalized' for DrIFT-cabalized-2.2.3.3...
[ 6 of 23] Compiling GenUtil          ( src/GenUtil.hs,
dist/build/DrIFT-cabalized/DrIFT-cabalized-tmp/GenUtil.o )

src/GenUtil.hs:291:14: Not in scope: `catch'

src/GenUtil.hs:294:15: Not in scope: `catch'

src/GenUtil.hs:388:15: Not in scope: `catch'
```

Should be something obvious, I've looked into it but still don't understand what happened with that catch. It is no longer in Prelude, but where should I take it from?

**Comment by ierton** [comment]
Ah, looks like I needed to report an issue to actually understand the problem. See https://github.com/ajhc/drift/pull/2
